"""Add fields to messages model

Revision ID: 1292a954a333
Revises: 1206bc4717db
Create Date: 2024-05-11 00:57:01.808787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1292a954a333'
down_revision: Union[str, None] = '1206bc4717db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIN_MESSAGES', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('AIN_MESSAGES', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('AIN_MESSAGES', 'messages')
    op.drop_column('AIN_MESSAGES', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIN_MESSAGES', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('AIN_MESSAGES', sa.Column('messages', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('AIN_MESSAGES', 'role')
    op.drop_column('AIN_MESSAGES', 'content')
    # ### end Alembic commands ###
