"""delete thread_id field to chat model

Revision ID: 596e621e9b72
Revises: 1292a954a333
Create Date: 2024-05-11 01:29:40.024648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596e621e9b72'
down_revision: Union[str, None] = '1292a954a333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AIN_CHATS', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIN_CHATS', sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
