"""add is visible field to messages model

Revision ID: 6bc551cb4138
Revises: 4bdaf51432f4
Create Date: 2024-05-12 01:49:18.357676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc551cb4138'
down_revision: Union[str, None] = '4bdaf51432f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIN_MESSAGES', sa.Column('is_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AIN_MESSAGES', 'is_visible')
    # ### end Alembic commands ###
